{"name": "تفشي_طبي_في_إيطاليا", "id": 7312579, "predecessors": [{"name": "الصحة_في_إيطاليا", "id": 940616}], "successors": [{"name": "جائحة_فيروس_كورونا_في_إيطاليا", "id": 7324806}]}