{"name": "فيضانات_في_آسيا_عقد_2020", "id": 8494843, "predecessors": [{"name": "العلم_في_القرن_21", "id": 1674152}], "successors": [{"name": "فيضانات_في_آسيا_2020", "id": 9129845}]}